- name: host
  type: group
  fields:
    - name: entity
      type: group
      fields:
        - name: attributes
          type: group
          fields:
            - name: managed
              type: boolean
        - name: lifecycle
          type: group
          fields:
            - name: last_activity
              type: date
